#Base de datos Actualizada
DROP DATABASE IF EXISTS SECUREMAPS;
CREATE DATABASE SECUREMAPS;
USE SECUREMAPS;

CREATE TABLE USUARIO 
	(USERNAME INT AUTO_INCREMENT PRIMARY KEY,
     NOMBRE VARCHAR(15),
	 CORREO	VARCHAR(30),
	 PSW VARCHAR(30));
     
CREATE TABLE PASOS
	(IDPASOS INT AUTO_INCREMENT PRIMARY KEY, 
     NUMPASOS INT, 
     FECHA DATETIME,
     IDUSUARIO INT,
     FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(USERNAME));
     
CREATE TABLE DIRECCION
	(IDDIRECCION INT AUTO_INCREMENT PRIMARY KEY,
     NOMBRE VARCHAR(30),
     NUMERO VARCHAR(5),
     CALLE VARCHAR(20),
     COLONIA VARCHAR(20),
     DELEGACION VARCHAR(20),
     DMAPA NVARCHAR(100));
     
CREATE TABLE LUGAR
	(IDLUGAR INT AUTO_INCREMENT PRIMARY KEY,
     IMAGEN LONGTEXT,
     SEGURIDAD INT,
     TIPO VARCHAR(15),
     IDDIRECCION INT,
     FOREIGN KEY(IDDIRECCION) REFERENCES DIRECCION(IDDIRECCION));
     
CREATE TABLE DIRECUSUARIO
	(ACTIVO BOOL,
     IDUSUARIO INT,
     IDDIRECUSU INT,
     FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(USERNAME),
     FOREIGN KEY(IDDIRECUSU) REFERENCES DIRECCION(IDDIRECCION));
     
CREATE TABLE VISITA
	(IDVISITA INT AUTO_INCREMENT PRIMARY KEY, 
     FECHA DATETIME,
     IDLUGAR INT, 
     IDUSUARIO INT,
     FOREIGN KEY(IDLUGAR) REFERENCES LUGAR(IDLUGAR),
     FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(USERNAME));
     
CREATE TABLE REVIEW
	(IDREVIEW INT AUTO_INCREMENT PRIMARY KEY, 
     PUNTUACION INT,
     COMENTARIO NVARCHAR(250),
     FECHAREVIEW DATETIME,
     IDLUGAR INT,
     IDUSUARIO INT,
     FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(USERNAME),
     FOREIGN KEY(IDLUGAR) REFERENCES LUGAR(IDLUGAR));
     
CREATE TABLE TRAYECTO
	(IDTRAYECTO INT AUTO_INCREMENT PRIMARY KEY,
     IDLUGAR INT,
     IDDIRECUSU INT,
     FOREIGN KEY(IDLUGAR) REFERENCES LUGAR(IDLUGAR),
     FOREIGN KEY(IDDIRECUSU) REFERENCES DIRECCION(IDDIRECCION));
     
CREATE TABLE HORARIO
	(IDHORARIO INT AUTO_INCREMENT PRIMARY KEY,
     DIA VARCHAR(10),
     APERTURA TIME,
     CIERRE TIME,
     IDLUGAR INT,
     FOREIGN KEY(IDLUGAR) REFERENCES LUGAR(IDLUGAR));     
     
CREATE TABLE HISTBUSQUEDA
	(IDHISTBUS INT AUTO_INCREMENT PRIMARY KEY,
     FECHA DATETIME,
     IDLUGAR INT,
     IDUSUARIO INT,
     FOREIGN KEY(IDLUGAR) REFERENCES LUGAR(IDLUGAR),
     FOREIGN KEY(IDUSUARIO) REFERENCES USUARIO(USERNAME));
     
select * from USUARIO;
insert into USUARIO values(
1, 'Fernando', 'fperez@gmail.com', 'OLA'
);